#pragma once

#include <common/types.h>
#include <common/bit.h>

#include <pci/address.h>

#define PCI_CONFIG_SPACE_SIZE 256
#define PCIE_CONFIG_SPACE_SIZE 4096

enum pci_config_reg {
    PCI_CONFIG_VENDOR_ID = 0x00,
        #define PCI_VENDOR_ID_NONE 0xFFFF

    PCI_CONFIG_DEVICE_ID = 0x02,
    PCI_CONFIG_COMMAND = 0x04,
        #define PCI_COMMAND_IO_ENABLE BIT_U16(0)
        #define PCI_COMMAND_MEMORY_ENABLE BIT_U16(1)
        #define PCI_COMMAND_BUS_MASTER_ENABLE BIT_U16(2)

    PCI_CONFIG_STATUS = 0x06,
    PCI_CONFIG_REVISION_ID = 0x08,

    PCI_CONFIG_CLASS_CODE = 0x08,
        #define PCI_CLASS_CODE_MASK MAKE_BIT_MASK_U32(31, 8)
        #define PCI_CLASS_CODE_INTERFACE_MASK MAKE_BIT_MASK_U32(15, 8)
        #define PCI_CLASS_CODE_CLASS_MASK MAKE_BIT_MASK_U32(31, 16)

    PCI_CONFIG_HEADER_TYPE = 0x0E,
    PCI_CONFIG_BAR0 = 0x10,
        #define PCI_BAR_IO_SPACE BIT_U32(0)
        #define PCI_BAR_IO_ADDRESS_MASK MAKE_BIT_MASK_U32(31, 2)
        #define PCI_BAR_MEMORY_ADDRESS_MASK MAKE_BIT_MASK_U32(31, 4)
};

#define PCI_MAKE_CLASS(base, sub) (((base) << 8) | (sub))

#define PCI_BASE_CLASS_COMMUNICATION 0x07
#define PCI_CLASS_SERIAL_CONTROLLER \
    PCI_MAKE_CLASS(PCI_BASE_CLASS_COMMUNICATION, 0x00)
#define PCI_CLASS_MODEM PCI_MAKE_CLASS(PCI_BASE_CLASS_COMMUNICATION, 0x03)

#define PCI_SERIAL_INTERFACE_16550 0x02
