function(setup_ubsan)
    set(CHECKS "")

    if (CONFIG_UBSAN_BOUNDS)
        list(APPEND CHECKS ${ULTRA_TOOLCHAIN_UBSAN_BOUNDS})
    endif ()
    if (CONFIG_UBSAN_SHIFT)
        list(APPEND CHECKS shift)
    endif ()
    if (CONFIG_UBSAN_SIGNED_OVERFLOW)
        list(APPEND CHECKS signed-integer-overflow)
    endif ()
    if (CONFIG_UBSAN_DIV_ZERO)
        list(APPEND CHECKS integer-divide-by-zero)
    endif ()
    if (CONFIG_UBSAN_UNREACHABLE)
        list(APPEND CHECKS unreachable)
    endif ()
    if (CONFIG_UBSAN_BOOL)
        list(APPEND CHECKS bool)
    endif ()

    if (CHECKS)
        list(JOIN CHECKS "," CHECKS)
        ultra_compile_options(-fsanitize=${CHECKS})
    endif ()

    if (CONFIG_TOOLCHAIN_CLANG)
        string(REPLACE "/" ";" SOURCE_DIR_PARTS "${CMAKE_SOURCE_DIR}")
        list(LENGTH SOURCE_DIR_PARTS SOURCE_DIR_DEPTH)
        ultra_compile_options(
            -fsanitize-undefined-strip-path-components=${SOURCE_DIR_DEPTH}
        )
    endif ()
endfunction()
