#pragma once

#include <common/types.h>

struct registers {
    /*
     * Registers, which must be restored by a function upon exit aka
     * "callee-preserved" or just "preserved".
     */
    u64 r15;
    u64 r14;
    u64 r13;
    u64 r12;
    u64 rbp;
    u64 rbx;

    /*
     * Registers, which may be used freely by any function. Must be explicitly
     * preserved by the caller if needed after the call. Aka "callee-clobbered"
     * or "scratch".
     */
    u64 r11;
    u64 r10;
    u64 r9;
    u64 r8;
    u64 rax;
    u64 rcx;
    u64 rdx;
    u64 rsi;
    u64 rdi;

    union {
        u64 error_code;
        u64 interrupt_idx;
        u64 syscall_number;
    };

    // Hardware frame (not generated by us), popped by iretq
    u64 rip;
    u64 cs;
    u64 flags;
    u64 rsp;
    u64 ss;
};
