add_test_cases(
    test_allocators.c
    test_parameter.c
    test_log_ring.c
    test_bit.c
    test_smbios.c
    test_list.c
    test_slist.c
    test_time.c
    test_rbtree.c
    test_cpu_mask.c
    test_cpu_mask_out_of_line.c
    test_mutex.c
    test_vector_alloc.c
    test_irq.c
)
