#pragma once

#include <common/helpers.h>
#include <common/attributes.h>
#include <linker.h>

#define INIT_CODE SECTION(FREE_AFTER_INIT_TEXT_SECTION)
#define INIT_DATA SECTION(FREE_AFTER_INIT_DATA_SECTION)
#define INIT_RODATA SECTION(FREE_AFTER_INIT_RODATA_SECTION)

#define CODE_REFERENCES_INIT_DATA SECTION(INIT_DATA_REFERENCE_TEXT_SECTION)
#define DATA_REFERENCES_INIT_DATA SECTION(INIT_DATA_REFERENCE_DATA_SECTION)
#define RODATA_REFERENCES_INIT_DATA SECTION(INIT_DATA_REFERENCE_RODATA_SECTION)
