#pragma once

#define REG_AFTER(x) ((x) + ULTRA_ARCH_WIDTH)

#define R15_OFFSET 0
#define R14_OFFSET REG_AFTER(R15_OFFSET)
#define R13_OFFSET REG_AFTER(R14_OFFSET)
#define R12_OFFSET REG_AFTER(R13_OFFSET)
#define RBP_OFFSET REG_AFTER(R12_OFFSET)
#define RBX_OFFSET REG_AFTER(RBP_OFFSET)

#define R11_OFFSET REG_AFTER(RBX_OFFSET)
#define R10_OFFSET REG_AFTER(R11_OFFSET)
#define R9_OFFSET  REG_AFTER(R10_OFFSET)
#define R8_OFFSET  REG_AFTER(R9_OFFSET)
#define RAX_OFFSET REG_AFTER(R8_OFFSET)
#define RCX_OFFSET REG_AFTER(RAX_OFFSET)
#define RDX_OFFSET REG_AFTER(RCX_OFFSET)
#define RSI_OFFSET REG_AFTER(RDX_OFFSET)
#define RDI_OFFSET REG_AFTER(RSI_OFFSET)

#define GP_REGS_END_OFFSET REG_AFTER(RDI_OFFSET)

#define AUX_OFFSET GP_REGS_END_OFFSET

#define IRETQ_FRAME_OFFSET REG_AFTER(AUX_OFFSET)

#define RIP_OFFSET   IRETQ_FRAME_OFFSET
#define CS_OFFSET    REG_AFTER(RIP_OFFSET)
#define FLAGS_OFFSET REG_AFTER(CS_OFFSET)
#define RSP_OFFSET   REG_AFTER(FLAGS_OFFSET)
#define SS_OFFSET    REG_AFTER(RSP_OFFSET)

#define IRETQ_FRAME_END_OFFSET REG_AFTER(SS_OFFSET)

#define INTERRUPT_FRAME_OFFSET(x) ((x) - IRETQ_FRAME_OFFSET)
#define INTERRUPT_FRAME_SIZE (IRETQ_FRAME_END_OFFSET - IRETQ_FRAME_OFFSET)
