name: CI
on: [push, pull_request]

jobs:
  lint-python-scripts:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install flake8 & mypy
        run: |
          sudo apt update
          sudo apt install python3 python3-pip
          export PIP_BREAK_SYSTEM_PACKAGES=1
          pip install flake8 mypy

      - name: Run flake8 on the project
        run: flake8 *.py scripts/*.py

      - name: Run mypy on the project
        run: |
          mypy --disallow-incomplete-defs --no-implicit-optional *.py

          # Do this because otherwise mypy complains:
          # 'Cannot find implementation or library stub for module named "image_utils.path_guesser"  [import-not-found]'
          pushd scripts
          mypy --disallow-incomplete-defs --no-implicit-optional *.py
          popd

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [i686, x86_64, "aarch64"]
        toolchain: [gcc, clang]
        exclude:
          # FIXME: the GCC build somehow ends up being corrupted with
          #        libexec/cc1 containing garbage data.
          - os: macos-latest
            toolchain: gcc

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - if: ${{ matrix.toolchain == 'gcc' }}
        name: Restore cache
        uses: actions/cache@v4.2.2
        env:
          gcc-version: 13.2.0
        with:
          path: "${{ github.workspace }}/toolchain/tools_${{ matrix.arch }}"
          key: "${{ runner.os }}-${{ runner.arch }}-${{ matrix.arch }}-gcc-${{ env.gcc-version }}"

      # TODO: maybe split these steps
      - name: Build platform toolchain & Kernel
        run: "${{ github.workspace }}/build.py --arch ${{ matrix.arch }} --toolchain ${{ matrix.toolchain }} --no-tune-native"

