include("${ULTRA_TOOLCHAIN_DIR}/toolchain_defaults.cmake")

set(ULTRA_TOOLCHAIN_ROOT ${CMAKE_CURRENT_LIST_DIR}/tools-gcc-${ULTRA_ARCH})
set(ULTRA_TOOLCHAIN_PATH ${ULTRA_TOOLCHAIN_ROOT}/bin)
set(ULTRA_TOOLCHAIN_PREFIX
    ${ULTRA_TOOLCHAIN_PATH}/${ULTRA_TARGET_PREFIX}-elf-)

set(CMAKE_C_COMPILER ${ULTRA_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${ULTRA_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_AR "${ULTRA_TOOLCHAIN_PREFIX}gcc-ar")
set(CMAKE_RANLIB "${ULTRA_TOOLCHAIN_PREFIX}gcc-ranlib")
set(CMAKE_NM "${ULTRA_TOOLCHAIN_PREFIX}gcc-nm")

set(ULTRA_TOOLCHAIN_LTO_FLAGS "-flto;-flto-partition=none")
